exclude:
- /.phan/config.php
- /application/javascript/admin/calendar.js
- /application/javascript/admin/ckeditor/.*
- /application/javascript/admin/lib/.*
- /source/.*
- /wip/admin/vcard.php
component_depth: 3
languages:
- javascript
- php
