version: "2"
plugins:
  csslint:
    enabled: true
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "phpcs.xml"
  phpmd:
    enabled: true
    config:
      rulesets: "phpmd.xml"
  sonar-php:
    enabled: true
]
