language: php

php:
  - 7.1
  - 7.2

before_install:
  - cd application

install:
  - composer install

before_script:
  - cd ..
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: phpunit

after_success:
  - travis_retry php application/vendor/bin/php-coveralls
  - php application/vendor/bin/codacycoverage clover build/logs/clover.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
