language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
  - $HOME/.composer/cache/files

before_install:
  - cd application

install:
  - composer install

before_script:
  - cd ..
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - cd application
  - vendor/bin/phpstan analyze --memory-limit=-1 --no-progress --level=max inc/ ../tests/
  - cd ..
  - phpunit

after_success:
  - travis_retry php application/vendor/bin/php-coveralls
  - bash <(curl -s https://codecov.io/bash)
  - php application/vendor/bin/codacycoverage clover build/logs/clover.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
