php:
  build: ./docker
  links:
  - db
  volumes:
  - ./application:/var/www/html

db:
  image: mariadb
  environment:
    MYSQL_DATABASE: agcms
    MYSQL_ALLOW_EMPTY_PASSWORD: 1
  ports:
  - 3306:3306
  volumes:
  - ./source/schema.sql:/docker-entrypoint-initdb.d/10schema.sql
  - ./source/seed.sql:/docker-entrypoint-initdb.d/20seed.sql

nginx:
  image: nginx:stable-alpine
  links:
  - php
  ports:
  - "80:80"
  volumes:
  - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
  - php
