<?php
require_once $_SERVER['DOCUMENT_ROOT'].'/admin/inc/logon.php';
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css"><!--
* {
    font-size:14px;
}
--></style>
</head>

<body><?php

require_once '../inc/mysqli.php';

function htmlUrlDecode($text)
{
    global $mysqli;

    $text = trim($text);

    //Double encode importand encodings, to survive next step and remove white space
    $text = preg_replace(
        array('/&lt;/u',  '/&gt;/u',  '/&amp;/u', '/\s+/u'),
        array('&amp;lt;', '&amp;gt;', '&amp;amp;', ' '),
        $text
    );

    //Decode IE style urls
    $text = html_entity_decode($text, ENT_QUOTES, 'UTF-8');

    //Decode Firefox style urls
    $text = rawurldecode($text);

    //atempt to make relative paths (generated by Firefox when copy pasting) in to absolute
    $text = preg_replace('/="[.]{2}\//iu', '="/', $text);

    return $text;
}

//Open database
$mysqli = new Simple_Mysqli(
    $GLOBALS['_config']['mysql_server'],
    $GLOBALS['_config']['mysql_user'],
    $GLOBALS['_config']['mysql_password'],
    $GLOBALS['_config']['mysql_database']
);

$mysqli = new Simple_Mysqli($GLOBALS['_config']['mysql_server'], $GLOBALS['_config']['mysql_user'], $GLOBALS['_config']['mysql_password'], $GLOBALS['_config']['mysql_database']);
$sider = $mysqli->fetchArray("SELECT id, text, beskrivelse FROM `sider` WHERE text != '' OR beskrivelse != ''");
$sider_nr = count($sider);
for ($i=0;$i<$sider_nr;$i++) {
    $mysqli->query("UPDATE `sider` SET `text` = '".htmlUrlDecode($sider[$i]['text'])."', `beskrivelse` = '".htmlUrlDecode($sider[$i]['beskrivelse'])."' WHERE `id` = ".$sider[$i]['id']." LIMIT 1");
    unset($sider[$i]);
    echo $i . ' - ';
}
$special = $mysqli->fetchArray("SELECT id, text FROM `special` WHERE text != ''");
$special_nr = count($special);
for ($i=0;$i<$special_nr;$i++) {
    $mysqli->query("UPDATE `special` SET `text` = '".htmlUrlDecode($special[$i]['text'])."' WHERE `id` = ".$special[$i]['id']." LIMIT 1");
    unset($special[$i]);
    echo $i . ' - ';
}

?>Done!
</body>
</html>
